# Generated by Django 3.2.6 on 2021-08-07 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('routeid', models.CharField(default='Missing', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('number', models.IntegerField(default=0, unique=True)),
                ('unique_id', models.CharField(default='Missing', max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Missing', max_length=50)),
                ('avg_dwelltime', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'stops',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('day_number', models.IntegerField(default=1)),
                ('temp_day', models.FloatField(default=0)),
                ('temp_min', models.FloatField(default=0)),
                ('temp_max', models.FloatField(default=0)),
                ('temp_night', models.FloatField(default=0)),
                ('temp_eve', models.FloatField(default=0)),
                ('temp_morn', models.FloatField(default=0)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('windDirection', models.FloatField(default=0)),
                ('windSpeed', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('clouds', models.FloatField(default=0)),
                ('precipitation', models.FloatField(default=0)),
                ('weatherid', models.IntegerField(default=0)),
                ('rain', models.FloatField(default=0.0)),
                ('main', models.CharField(default='Missing', max_length=20)),
                ('description', models.CharField(default='Missing', max_length=50)),
                ('scraped_on', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'weather',
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_yn', models.BooleanField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('percent_of_route', models.FloatField(default=0)),
                ('routeid', models.ForeignKey(default='Missing', on_delete=django.db.models.deletion.CASCADE, related_name='routestops', to='api.route')),
                ('stopnumber', models.ForeignKey(default='Missing', on_delete=django.db.models.deletion.CASCADE, related_name='routestops', to='api.stop', to_field='number')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='Missing', max_length=350)),
                ('user', models.ForeignKey(default='Missing', on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopid', models.ForeignKey(default='Missing', on_delete=django.db.models.deletion.CASCADE, related_name='favstops', to='api.stop')),
                ('user', models.ForeignKey(default='Missing', on_delete=django.db.models.deletion.CASCADE, related_name='favstops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='favouritestop',
            constraint=models.UniqueConstraint(fields=('user', 'stopid'), name='unique_favourite'),
        ),
    ]
