# Generated by Django 3.2.6 on 2021-08-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='accuracy_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='clean_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='routeid',
            field=models.ForeignKey(default='Missing', on_delete=django.db.models.deletion.CASCADE, related_name='routereview', to='api.route'),
        ),
        migrations.AddField(
            model_name='review',
            name='speed_rating',
            field=models.IntegerField(default=0),
        ),
    ]
