# Generated by Django 3.2.4 on 2021-06-28 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('windDirection', models.FloatField(default=0)),
                ('windSpeed', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('clouds', models.FloatField(default=0)),
                ('precipiation', models.FloatField(default=0)),
                ('weatherid', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=datetime.date(2021, 6, 28))),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
    ]
