# Generated by Django 3.2.6 on 2021-08-08 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210807_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeid', models.ForeignKey(default='Missing', on_delete=django.db.models.deletion.CASCADE, related_name='favroutes', to='api.route')),
                ('user', models.ForeignKey(default='Missing', on_delete=django.db.models.deletion.CASCADE, related_name='favroutes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='favouriteroute',
            constraint=models.UniqueConstraint(fields=('user', 'routeid'), name='unique_favourite_route'),
        ),
    ]
