# Generated by Django 3.2.4 on 2021-06-28 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_weather_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 11, 58, 50, 524473, tzinfo=utc)),
        ),
    ]
