# Generated by Django 3.2.4 on 2021-06-28 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_weather_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='precipiation',
            new_name='precipitation',
        ),
        migrations.AlterField(
            model_name='weather',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 12, 7, 11, 106613, tzinfo=utc)),
        ),
    ]
