# Generated by Django 3.2.4 on 2021-06-28 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210628_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='weather',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
