# Generated by Django 3.2.4 on 2021-06-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210628_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='created_date',
        ),
    ]
