# Generated by Django 3.2.4 on 2021-06-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_weather_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='temp_day',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_eve',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_max',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_morn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weather',
            name='temp_night',
            field=models.FloatField(default=0),
        ),
    ]
