# Generated by Django 3.2.4 on 2021-07-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210701_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='created_date',
            new_name='scraped_on',
        ),
    ]
