# Generated by Django 3.2.4 on 2021-07-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_created_date_weather_scraped_on'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weather',
            table='weather',
        ),
    ]
