# Generated by Django 3.2.4 on 2021-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_weather_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
    ]
