# Generated by Django 3.2.4 on 2021-07-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_weather_day_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='id',
        ),
        migrations.AlterField(
            model_name='weather',
            name='day_number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
