# Generated by Django 3.2.4 on 2021-07-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210701_1328'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('day_number', 'scraped_on')},
        ),
    ]
