# Generated by Django 3.2.4 on 2021-07-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_weather_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set(),
        ),
    ]
