# Generated by Django 3.2.4 on 2021-07-01 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_weather_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weather',
            name='scraped_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('day_number', 'scraped_on')},
        ),
    ]
