# Generated by Django 3.2.4 on 2021-07-05 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210701_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='weather',
            name='scraped_on',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set(),
        ),
    ]
