# Generated by Django 3.2.5 on 2021-07-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210705_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Missing', max_length=50)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('unique_id', models.CharField(default='Missing', max_length=15)),
            ],
            options={
                'db_table': 'stops',
            },
        ),
    ]
