# Generated by Django 3.2.5 on 2021-07-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_stops'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stops',
            new_name='Stop',
        ),
    ]
