# Generated by Django 3.2.5 on 2021-07-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_stops_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
