# Generated by Django 3.2.5 on 2021-07-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210714_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='number',
            field=models.IntegerField(default='0'),
        ),
    ]
