name: Testing and Linting on Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  django:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install
      - name: Lint with flake8
        run: |
          pipenv install flake8
          # stop the build if there are Python syntax errors or undefined names
          pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Django Testing project
        run: |
          pipenv run python3 manage.py test # Don't forget to run tests

  vue:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
      - run: yarn test:unit
      - run: yarn test:e2e
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Audit live URL
        uses: jakejarvis/lighthouse-action@master
        with:
          url: "https://cityroute.ml/"
      - name: Upload results as an artifact
        uses: actions/upload-artifact@master
        with:
          name: report
          path: "./report"
